apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: bXl1c2Vy    # base64 of "myuser"
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==  # base64 of "mypassword"
  POSTGRES_DB: bXlkYXRhYmFzZQ==   # base64 of "mydatabase"